{% set name = "nbdev" %}
{% set version = "2.3.28" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nbdev-{{ version }}.tar.gz
  sha256: 053645717eff98f0e06a12bd2b65a25505162b994586d1f87f8222960208c20c

build:
  noarch: python
  entry_points:
    - nbdev_create_config=nbdev.config:nbdev_create_config
    - nbdev_update=nbdev.sync:nbdev_update
    - nbdev_update_license=nbdev.cli:nbdev_update_license
    - nbdev_export=nbdev.doclinks:nbdev_export
    - nbdev_fix=nbdev.merge:nbdev_fix
    - nbdev_merge=nbdev.merge:nbdev_merge
    - nbdev_trust=nbdev.clean:nbdev_trust
    - nbdev_clean=nbdev.clean:nbdev_clean
    - nbdev_install_hooks=nbdev.clean:nbdev_install_hooks
    - nbdev_filter=nbdev.cli:nbdev_filter
    - nbdev_sidebar=nbdev.quarto:nbdev_sidebar
    - nbdev_test=nbdev.test:nbdev_test
    - nbdev_new=nbdev.cli:nbdev_new
    - nbdev_migrate=nbdev.migrate:nbdev_migrate
    - nbdev_install_quarto=nbdev.quarto:install_quarto
    - nbdev_install=nbdev.quarto:install
    - nbdev_docs=nbdev.quarto:nbdev_docs
    - nbdev_preview=nbdev.quarto:nbdev_preview
    - nbdev_prepare=nbdev.quarto:prepare
    - nbdev_readme=nbdev.quarto:nbdev_readme
    - nbdev_release_gh=nbdev.release:release_gh
    - nbdev_release_git=nbdev.release:release_git
    - nbdev_changelog=nbdev.release:changelog
    - nbdev_pypi=nbdev.release:release_pypi
    - nbdev_conda=nbdev.release:release_conda
    - nbdev_release_both=nbdev.release:release_both
    - nbdev_bump_version=nbdev.release:nbdev_bump_version
    - nbdev_requirements=nbdev.release:write_requirements
    - nbdev_proc_nbs=nbdev.quarto:nbdev_proc_nbs
    - nbdev_help=nbdev.cli:chelp
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - asttokens
    - astunparse
    - execnb >=0.1.4
    - fastcore >=1.5.27
    - python >=3.7
    - pyyaml
    - watchdog
    - ghapi >=1.0.3

test:
  imports:
    - nbdev
  commands:
    - pip check
    - nbdev_create_config --help
    - nbdev_update --help
    - nbdev_update_license --help
    - nbdev_export --help
    - nbdev_fix --help
    - nbdev_merge --help
    - nbdev_trust --help
    - nbdev_clean --help
    - nbdev_install_hooks --help
    - nbdev_filter --help
    - nbdev_sidebar --help
    - nbdev_test --help
    - nbdev_new --help
    - nbdev_migrate --help
    - nbdev_install_quarto --help
    - nbdev_install --help
    - nbdev_docs --help
    - nbdev_preview --help
    - nbdev_prepare --help
    - nbdev_readme --help
    - nbdev_release_gh --help
    - nbdev_release_git --help
    - nbdev_changelog --help
    - nbdev_pypi --help
    - nbdev_conda --help
    - nbdev_release_both --help
    - nbdev_bump_version --help
    - nbdev_requirements --help
    - nbdev_proc_nbs --help
    - nbdev_help --help
  requires:
    - pip

about:
  home: https://nbdev.fast.ai/
  dev_url: https://github.com/fastai/nbdev
  summary: Create delightful software with Jupyter Notebooks
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - corneliusroemer
    - thewchan
